name: Pipeline-1
on: push

jobs:
  CI:                                                # Job ID (mandatory)
    name: Pipeline Job                               # Friendly display name (optional)
    runs-on: ubuntu-latest
    steps:
    - name: plan
      run: | 
        echo "first run"
    - name: apply
      run: | 
        echo "second run"
