name: Manual Pipeline
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Where do you want to run this?"
                required: true
                default: "dev"
                type: choice
                options:
                    - dev
                    - prod
                    - nonprod
                    - test

            action:
                description: "What should this pipeline do?"
                required: true
                default: "plan"
                type: choice
                options:
                    - plan
                    - apply

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: plan
              uses: actions/checkout@v2

            - name: apply
              run: |
                  echo "this is second step manual pipeline run"
